version: '3.8'
services:
  flaskweb:
    build: .
    container_name: ateflearns_flaskweb
    volumes:
      - source_code:/flaskapp
    networks:
      - backend
    expose:
      - 5000

  nginx:
    image: nginx:latest
    container_name: ateflearns_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flaskweb
    networks:
      - backend

  postgres:
    image: postgres:latest
    container_name: ateflearns_postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - backend

volumes:
  source_code:
    name: ateflearns_sourcecode
  postgres_data:
    name: ateflearns_dbvolume

networks:
  backend:
    name: ateflearns_backendnet
